export const RICH_BLACK_COLOR = '#343434'
export const ALICE_BLUE_COLOR = '#F9FCFF'
export const MEDIUM_STATE_BLUE_COLOR = '#736CED'
export const WHITE_COLOR = '#FFFFFF'
export const GREY_COLOR = '#A5A5A5'